development: &base
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        connect_timeout: 15
test:
  <<: *base
  clients:
    default:
      uri: <%= ENV['MONGODB_TEST__URI'] %>
production:
  <<: *base
