development: &base
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        connect_timeout: 15
production:
  <<: *base
test:
  <<: *base
  clients:
    default:
      uri: <%= ENV['MONGODB_TEST_URI'] %>
